language: python
python:
- 3.6
- 3.7
- 3.8
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: peterk87
  password:
    secure: PHuYN0I1U4JOEsK3NX4vX2shi5PoqAXBchHOOkodhtE5RcANEmn8Z/AuinYimTGgolN2G/Y5F8LsTiBB5qb22BziQnM33igZbyV1FE+nzxrYuli1S14+zLm7ttLfLtjh+Kkrb0qUOPoqBtYqHlc5xrSOejgEMy5gvgcyicJeuogPkXUcVZocQBSFhAV8naj49eGxAhDCptHd6DH5ebFfzyi4Rqr3pb5nhMC62+5kDgBy10906PyGGx3Nk9Ado5ak3xC7QSvOFBwidtRZztTJks7GC609nJk2N3hQZTJYSqHGHreFS2mlyA0/yd6SH/58kCyrfsC56HhmNod/jZhNBo6+/+VSysn2EisNXsgGI3KY9/eBMo3WKym37Ujzrk9KjETrk4UPggypgqQNt025k8YISx6U2FL6PM/msarMg6wj6oMRLEzYOHUJCmAnXVQCFHyf/ZLBn6KpkelkwnLD96lzId2LDE173qViaRZDnIlwwAWBPLCS1ddFtSizcxiBVwOLAeDO9cSjSb5nn1v9n0+2hFNBYr9wqTTbu/GoxAO8q96DWbtTRixzhhPsMztj9gryatvgvxnEI0bVDKNtwjWgkJKpQbMAygtJ2x1E54joxy384sX4XOqC/QZkpScue1QhYM2kX7+0RxDfVOJvE4iOuCFP0bClhQWSFfr6jxk=
  on:
    tags: true
    repo: peterk87/shiptv
    python: 3.8
